services:
  - type: web
    name: salon-bot
    env: python
    region: frankfurt # или другой регион
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"